# SPDX-FileCopyrightText: 2024 Luflosi <dyndnsd@luflosi.de>
# SPDX-License-Identifier: CC0-1.0

name: "CI"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@9a59e15a74545c99a626ba594edcd0d02189e670
      - uses: DeterminateSystems/flake-checker-action@c12af2160982bfd63f983db063e92c66836b1c73
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c
        with:
          name: luflosi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix flake check`
        run: nix flake check -L
