# SPDX-FileCopyrightText: 2024 Luflosi <zonewatch@luflosi.de>
# SPDX-License-Identifier: CC0-1.0

name: "Publish a flake to flakestry"
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
      - "v?[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish"
        type: "string"
        required: true
jobs:
  flakestry-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: flakestry/flakestry-publish@fc5c0f9151687306d169606859530ba9e5ff2501
        with:
          version: "${{ inputs.tag || github.ref_name }}"
